### ISSUE TITLE
Adopt formatOnSave changes 

### ISSUE THREAD

**Issue by jrieken** [taichi/react-beautify#12]
Since version 1.6 VS Code has a format on save option. It works by calling the registered formatting provider for the language in question and most _importantly_ it happens _before_ the file is saved to disk, not causing additional fs writes and event cascades. 

Please adopt [this code](https://github.com/taichi/react-beautify/blob/master/src/extension.ts#L52) code by either removing it and trusting the new `editor.formatOnSave`-setting or by using the new `onWillSaveTextDocument`-event. 

See https://code.visualstudio.com/updates#_format-on-save, https://github.com/Microsoft/vscode/issues/12449, and https://github.com/Microsoft/vscode/issues/239

**Comment by taichi** [comment]
thanks for your information, i'll try it.

**Comment by jrieken** [comment]
Cool - let me know if you need help or support

**Comment by taichi** [comment]
@jrieken done it #13 
do you have some advice?

**Comment by jrieken** [comment]
Looks proper - tho note that there is the global `editor.formatOnSave`-setting. So when both settings are true (the former and the one from this extension) you will be called twice. That you can prevent from not listening on any save event anymore (VS Code will then call your extension)
